name: Continuous Integration

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build-windows:

    name: Windows Build
    runs-on: windows-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup Nuget
      uses: Nuget/setup-nuget@v1.0.5

    - name: Restore nuget packages
      run: nuget restore Moq.Extensions/Moq.Extensions.csproj

    - name: Build app for release
      run: msbuild Moq.Extensions\Moq.Extensions.csproj -t:rebuild -verbosity:diag -property:Configuration=Release