name: Continuous Integration (PR)

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - name: Setup Nuget
        uses: nuget/setup-nuget@v1

      - name: Restore nuget packages
        run: nuget restore ${{ vars.SOLUTION_NAME }}

      - name: Build
        run: dotnet build ${{ vars.SOLUTION_NAME }} --configuration Release
          #run: msbuild ${{ vars.SOLUTION_NAME }} -t:rebuild -verbosity:diag -property:Configuration=Release

      - name: Test
        run: dotnet test ${{ vars.SOLUTION_NAME }} --no-build --configuration Release
